### PR TITLE
Setup Label Studio in local and automatically import the images for annotations from local & created scheduler for model training

### LINKED ISSUE #28: Setup Label Studio in local and figure out a way to automatically import images to be annotated from a temp location for now.

### LINKED ISSUE #29: Create a scheduler to pick up images submitted with Feedback from Mongo.

### LINKED ISSUE #30: Integrate the above to complete the flow.

### PR DESCRIPTION
**Pull request by who-ash**
Added the documentation for Setting up Label Studio in local and automatically import the images for annotations from local.
Created the scheduler for model training and added the documentation for setup and understanding

closes: #28 
closes: #29 
closes: #30

### CODE REVIEW

**Comment by Ashish9738** [comment]
Hey @Tejas-ChandraShekarRaju, Gone through the issue and able to setup label studio and import the images and documented the steps for the above issue.

Using JSON file: 
import__1

Using Cloud storage:
import__2

**Comment by Tejas-ChandraShekarRaju** [comment]
Good Job, @Ashish See if you can pick up the scheduler as well.

**Comment by Ashish9738** [comment]
Hey @Tejas-ChandraShekarRaju, New commit resolves the scheduler stuff and also added the documentation for testing and setup.

**Comment by Ashish9738** [comment]
Uploading label-studio-test.mp4…

**Comment by Ashish9738** [comment]
Uploading label-studio-test.mp4…

**Pull request closed without merging**
